force-app/main/default/objects/Persona__c/Persona__c.object-meta.xml
<CustomObject>
    <description>Used for Persona content in the Ask Astro floating head component</description>
    <label>Persona</label>
    <nameField>
        <label>Persona Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Persona__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <defaultValue>&apos;Lauren Bailey&apos;</defaultValue>
    <inlineHelpText>Name used in the details pop-up from the Astro floating head. e.g. the name of a person &quot;Lauren Bailey&quot;. Used by the default Flow &apos;Ask_Astro_Persona&apos;.</inlineHelpText>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Persona__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <defaultValue>&apos;laurenbailey&apos;</defaultValue>
    <inlineHelpText>Name of the static resource for the image used in the Astro floating head</inlineHelpText>
    <label>Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Persona__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>The Persona Role. Might be the same as the Persona Name such as: &quot;Partner&quot;, &quot;Customer&quot;; or a title: &quot;Sales Executive&quot;, &quot;Operations Manager&quot;. Used by the default Flow &apos;Ask_Astro_Persona&apos;.</inlineHelpText>
    <label>Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Persona__c/fields/Where_Are_We__c.field-meta.xml
<CustomField>
    <fullName>Where_Are_We__c</fullName>
    <label>Where Are We?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AstroController.cls
global without sharing class AstroController {

    @AuraEnabled
    public static Persona__c getPersona(String personaName) {

        System.debug('AstroController > getPersona - personaName: ' + personaName);
        Persona__c persona;

        List<Persona__c> personas = [
                SELECT Id, Name, Full_Name__c, Role__c, Image__c, Where_Are_We__c 
                FROM Persona__c
                WHERE Name = :personaName
        ];

        if (personas.size() > 0) {
            persona = personas.get(0);           
            if (persona.Full_Name__c == null) { persona.Full_Name__c = 'blank'; }
            if (persona.Role__c == null) { persona.Role__c = 'blank'; }
            if (persona.Image__c == null) { persona.Image__c = 'blank'; }
            if (persona.Where_Are_We__c == null) { persona.Where_Are_We__c = 'blank'; }
        }
        System.debug('AstroController > getPersona - persona: ' + persona);

        return persona;

    } // end getPersona
    
    @InvocableMethod(label='Get Persona')
    global static List<Persona__c> getPersonaDetails(List<String> personaName) {
        
        List<Persona__c> personaResponse = new List<Persona__c>();
        for (String name : personaName) {
        	System.debug('AstroController > getPersonaDetails - personaName: ' + name);
        	Persona__c persona = getPersona(name);
            personaResponse.add(persona);
        }
        
        return personaResponse;
        
    } // end getPersonaDetails   
    
    
}