force-app/main/default/objects/Persona__c/Persona__c.object-meta.xml
<CustomObject>
    <description>Used for Persona content in the Ask Astro floating head component</description>
    <label>Persona</label>
    <nameField>
        <label>Persona Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Persona__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <defaultValue>&apos;Lauren Bailey&apos;</defaultValue>
    <inlineHelpText>Name used in the details pop-up from the Astro floating head. e.g. the name of a person &quot;Lauren Bailey&quot;. Used by the default Flow &apos;Ask_Astro_Persona&apos;.</inlineHelpText>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Persona__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>The Persona Role. Might be the same as the Persona Name such as: &quot;Partner&quot;, &quot;Customer&quot;; or a title: &quot;Sales Executive&quot;, &quot;Operations Manager&quot;. Used by the default Flow &apos;Ask_Astro_Persona&apos;.</inlineHelpText>
    <label>Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AstroController_Test.cls
@isTest
private class AstroController_Test {

    @isTest static void test() {
        
        System.debug('AstroController_Test >> start');
        
        // data
        String personaName = 'Service Agent';
        Persona__c p = new Persona__c(Name = personaName);
        p.Full_Name__c = 'Ryan Cox';
        p.Role__c = personaName;
		insert p;
        
        // test
        Test.startTest();
        List<String> personaNames = new List<String>{ personaName };
        List<Persona__c> personas = AstroController.getPersonaDetails(personaNames);
        System.assertEquals(personas.size(), 1);
        Test.stopTest();
        
        System.debug('AstroController_Test >> complete');
        
    }
    
} // end AstroController_Test